-- Seed de las 200 frases motivacionales (ANEXO A del documento de contexto)
insert into public.phrases (id, texto) values
  (1, 'Nadie va a venir a salvarte. Levantate vos.'),
  (2, 'La cama caliente es la tumba de tus sueños. Salí de ahí.'),
  (3, 'Hoy no se negocia. O entrenás o te mentís.'),
  (4, 'El que empieza mil veces nunca llega. Sostené.'),
  (5, 'Tu excusa favorita ya la escuchaste mil veces. Cambiá el disco.'),
  (6, 'Dolor de hoy, orgullo de mañana. Elegí.'),
  (7, 'No necesitás ganas. Necesitás moverte igual.'),
  (8, 'La disciplina te va a llevar donde la motivación te abandona.'),
  (9, 'Cada día que aflojás, alguien con tu mismo sueño no aflojó.'),
  (10, 'No sos vago. Sos alguien que todavía no decidió en serio.'),
  (11, 'El cuerpo se queja, la mente manda. Vos decidís quién gobierna.'),
  (12, 'Lo difícil es lo que te cambia. Lo fácil te deja igual.'),
  (13, 'Nadie te debe nada. Andá a buscarlo vos.'),
  (14, 'Si esperás estar listo, nunca vas a empezar. Empezá roto.'),
  (15, 'La garra no se hereda, se entrena todos los días.'),
  (16, 'Hoy es un partido. Jugalo como si fuera el último.'),
  (17, 'El sofá no te va a extrañar. Andá.'),
  (18, 'Podés estar cansado o podés estar orgulloso. No las dos.'),
  (19, 'Tu versión de mañana está mirando lo que hacés hoy.'),
  (20, 'Dejá de esperar el lunes. El lunes sos vos, ahora.'),
  (21, 'Nadie construyó nada grande sintiéndose cómodo.'),
  (22, 'La constancia le gana al talento cuando el talento se relaja.'),
  (23, 'Fallaste ayer. ¿Y? Hoy se juega igual.'),
  (24, 'El que se rinde nunca sabe qué tan cerca estaba.'),
  (25, 'No es falta de tiempo. Es falta de prioridad. Sé honesto.'),
  (26, 'Sudá ahora o arrepentite después. Vos elegís la moneda.'),
  (27, 'Tu mente te va a pedir parar mucho antes que tu cuerpo.'),
  (28, 'Levantarte temprano no te hace mejor. Te hace disponible.'),
  (29, 'La comodidad es cara. Te cobra tus sueños.'),
  (30, 'No busques motivación. Buscá disciplina y quedate ahí.'),
  (31, 'El progreso es aburrido. Por eso pocos llegan.'),
  (32, 'Cada repetición que no querías hacer es la que cuenta.'),
  (33, 'Hoy alguien más débil que vos no entrenó. No seas ese.'),
  (34, 'El respeto propio se gana cumpliendo lo que te prometiste.'),
  (35, 'Nadie te va a aplaudir por empezar. Te van a respetar por sostener.'),
  (36, 'La incomodidad es la puerta. Entrá.'),
  (37, 'Vas a querer parar. Ese es el momento exacto de seguir.'),
  (38, 'Tu potencial no sirve de nada si lo dejás dormir.'),
  (39, 'El que entrena cansado se hace fuerte. El que descansa cansado se hace excusa.'),
  (40, 'No naciste para vivir en piloto automático. Despertá.'),
  (41, 'La verdad incomoda: podés más de lo que hacés.'),
  (42, 'Cada día ganado es un ladrillo. Cada día perdido es una grieta.'),
  (43, 'Nadie recuerda al que casi lo hizo.'),
  (44, 'Tu cuerpo es el único lugar donde vas a vivir siempre. Cuidalo.'),
  (45, 'El dolor es información, no una orden de parar.'),
  (46, 'Andá aunque no tengas ganas. Sobre todo si no tenés ganas.'),
  (47, 'Empezaste esto por algo. Volvé a ese por qué.'),
  (48, 'La derrota real no es perder un día. Es abandonar.'),
  (49, 'Hoy tu única competencia sos vos de ayer.'),
  (50, 'Dejá de mirar a los demás. Corré tu propia carrera.'),
  (51, 'La grasa no se va con quejas. Se va con laburo.'),
  (52, 'El que madruga no gana. Gana el que madruga y hace algo.'),
  (53, 'No hay atajo. Hay laburo o hay mentira.'),
  (54, 'Cada NO a la excusa es un SÍ a tu mejor versión.'),
  (55, 'La constancia es la única magia que existe.'),
  (56, 'Tu futuro no se construye el lunes. Se construye hoy.'),
  (57, 'Movete. El movimiento mata a la duda.'),
  (58, 'El campeón no es el que nunca cae. Es el que se levanta más rápido.'),
  (59, 'Sé más fuerte que tu excusa más creativa.'),
  (60, 'Nadie que valga la pena la tuvo fácil.'),
  (61, 'Hoy sudás vos, no tu vecino. Los resultados también son tuyos.'),
  (62, 'La disciplina pesa gramos. El arrepentimiento pesa toneladas.'),
  (63, 'Dejaste de intentar y le llamaste "realismo". No te mientas.'),
  (64, 'El cuerpo cambia cuando la mente se cansa de excusas.'),
  (65, 'Ganar el día no es fácil. Por eso vale.'),
  (66, 'La zona de confort te queda chica. Salí.'),
  (67, 'Vos contra vos. El único partido que importa.'),
  (68, 'Cada gota de sudor es una queja que no diste.'),
  (69, 'Hoy no busques perfecto. Buscá hecho.'),
  (70, 'El hábito se construye los días que no querés.'),
  (71, 'No te preguntes si podés. Ya sabés que sí. Preguntate si vas a hacerlo.'),
  (72, 'La constancia es rebelde en un mundo de gente que abandona.'),
  (73, 'Menos hablar de cambiar. Más cambiar callado.'),
  (74, 'Tu peor día entrenando le gana a tu mejor día en el sillón.'),
  (75, 'El respeto empieza por el que te devuelve el espejo.'),
  (76, 'Nadie te va a hacer el trabajo. Ni falta que hace: es tuyo.'),
  (77, 'La garra guaraní no pide permiso. Actúa.'),
  (78, 'Perdiste ayer. Bien. Hoy tenés revancha.'),
  (79, 'El que quiere, encuentra la forma. El que no, encuentra la excusa.'),
  (80, 'Cada día es un round. No tires la toalla en el primero.'),
  (81, 'La comodidad es un préstamo. Te lo cobran con intereses.'),
  (82, 'No entrenás para hoy. Entrenás para el que vas a ser.'),
  (83, 'Dejá de esperar ganas. Las ganas vienen después de empezar.'),
  (84, 'El sudor de hoy es la confianza de mañana.'),
  (85, 'Nadie sube la montaña mirándola. Se sube caminando.'),
  (86, 'Tu mente miente cuando está cómoda. No le creas.'),
  (87, 'La diferencia entre vos y tu meta es lo que hacés hoy.'),
  (88, 'Ganá el día chico y el mes grande se gana solo.'),
  (89, 'El que aguanta, gana. Simple y brutal.'),
  (90, 'No sos el cansancio que sentís. Sos la decisión que tomás.'),
  (91, 'Cada excusa que matás te hace más fuerte.'),
  (92, 'Hoy tenés dos opciones: crecer o justificarte.'),
  (93, 'El progreso no se ve en el espejo cada día. Se ve al final.'),
  (94, 'Levantate. El mundo no espera a nadie.'),
  (95, 'La constancia aburre y transforma. Elegí transformarte.'),
  (96, 'No hay días perdidos si aprendés a volver.'),
  (97, 'Tu cuerpo aguanta más de lo que tu cabeza cree.'),
  (98, 'El que entrena con lluvia entrena distinto. Sé ese.'),
  (99, 'Dejá de contarle a todos tu plan. Mostralo con hechos.'),
  (100, 'La mitad del camino es la más solitaria. Aguantá.'),
  (101, 'Hoy nadie te obliga. Por eso cuenta doble.'),
  (102, 'El fuerte no nace. Se hace, día por día.'),
  (103, 'Cada mañana elegís: guerrero o espectador.'),
  (104, 'La disciplina es amor propio en acción.'),
  (105, 'Vas a fallar. La pregunta es si vas a volver.'),
  (106, 'Nadie te va a respetar más de lo que te respetás vos.'),
  (107, 'El músculo se rompe para hacerse fuerte. Igual que vos.'),
  (108, 'No te compares con el de al lado. Compárate con tu excusa de ayer.'),
  (109, 'Ganar el partido de hoy es todo lo que te pido.'),
  (110, 'El que sostiene 60 días cambia para siempre.'),
  (111, 'La incomodidad de hoy es la libertad de mañana.'),
  (112, 'Dale al cuerpo lo que la mente quiere evitar.'),
  (113, 'No es el más talentoso. Es el que no falta.'),
  (114, 'Cada día que cumplís, tu palabra vale más.'),
  (115, 'El sillón es cómodo porque no te lleva a ningún lado.'),
  (116, 'Sé el que aparece. Siempre. Sobre todo cuando duele.'),
  (117, 'Tu excusa es válida. Tu resultado también lo va a ser. Elegí cuál querés.'),
  (118, 'La rutina no es cárcel. Es la escalera.'),
  (119, 'Hoy transpirás vos por el sueño que es tuyo.'),
  (120, 'El campeón entrena lo que el perezoso posterga.'),
  (121, 'No pares cuando estés cansado. Pará cuando termines.'),
  (122, 'La grandeza vive del otro lado de la comodidad.'),
  (123, 'Cada día es una elección. Hoy elegí bien.'),
  (124, 'El que se levanta a las 6 mientras otros duermen, ya ganó algo.'),
  (125, 'Tus músculos olvidan la excusa. Recuerdan el trabajo.'),
  (126, 'No busques aplausos. Buscá progreso.'),
  (127, 'La constancia es la venganza silenciosa contra el que dudó de vos.'),
  (128, 'Hoy peleás contra la versión cómoda de vos mismo.'),
  (129, 'El sudor no miente. La excusa sí.'),
  (130, 'Entrená como si el que dudó de vos estuviera mirando.'),
  (131, 'No te falta capacidad. Te falta decisión.'),
  (132, 'Cada día ganado te hace más difícil de romper.'),
  (133, 'El descanso es parte del plan, no la excusa del plan.'),
  (134, 'La disciplina no espera que tengas ganas. Actúa igual.'),
  (135, 'Levantá el culo del sillón. Tu futuro te lo agradece.'),
  (136, 'El que corre cuando no quiere, gana cuando importa.'),
  (137, 'Hoy no se trata de ganas. Se trata de palabra.'),
  (138, 'Nadie llega lejos abandonando en la primera cuesta.'),
  (139, 'Tu cuerpo es tu templo o tu excusa. Vos decidís.'),
  (140, 'Cada repetición cuenta. Sobre todo la última.'),
  (141, 'El respeto se suda, no se pide.'),
  (142, 'Fallar no te define. Rendirte sí.'),
  (143, 'La comodidad es enemiga silenciosa. Reconocela y peleá.'),
  (144, 'Hoy hacé lo que tu yo del futuro va a agradecer.'),
  (145, 'El que aguanta el aburrimiento del progreso, gana.'),
  (146, 'No hay motivación eterna. Hay disciplina diaria.'),
  (147, 'Movete aunque sea poco. Poco todos los días es mucho.'),
  (148, 'La verdad: te estás acostumbrando a menos de lo que podés.'),
  (149, 'Cada día que cumplís, la excusa pierde fuerza.'),
  (150, 'El guerrero no espera condiciones perfectas. Pelea con lo que tiene.'),
  (151, 'Tu mejor versión no llega sola. La construís vos.'),
  (152, 'Nadie dijo que iba a ser fácil. Dijeron que iba a valer la pena.'),
  (153, 'Hoy transpirá. Mañana agradecé.'),
  (154, 'La disciplina es elegir lo que querés a largo plazo sobre lo que querés ahora.'),
  (155, 'El que no falla los días fáciles no falla los difíciles.'),
  (156, 'Cada mañana es una cancha nueva. Salí a ganarla.'),
  (157, 'No te rindas en el kilómetro que estabas por romper tu récord.'),
  (158, 'La fuerza no se pide prestada. Se construye.'),
  (159, 'Hoy tu enemigo es el "mañana lo hago".'),
  (160, 'El cuerpo sigue a la mente. Ordenale bien.'),
  (161, 'Cada día ganado es una promesa cumplida a vos mismo.'),
  (162, 'No sos lo que decís que vas a hacer. Sos lo que hacés.'),
  (163, 'La incomodidad es el precio de entrada. Pagalo.'),
  (164, 'El que suda en silencio grita con resultados.'),
  (165, 'Hoy elegí ser difícil de vencer.'),
  (166, 'La constancia convierte lo imposible en rutina.'),
  (167, 'Nadie te va a cargar hasta la meta. Caminá vos.'),
  (168, 'El descanso lo ganás entrenando, no evitando.'),
  (169, 'Cada excusa es una cadena. Cortala.'),
  (170, 'Tu potencial se ríe de tu comodidad. Callale la boca.'),
  (171, 'Hoy no es un día más. Es un día menos para tu meta.'),
  (172, 'El que empieza y sostiene ya es distinto al resto.'),
  (173, 'La garra se demuestra el día que menos querés.'),
  (174, 'No entrenás para gustarle a nadie. Entrenás para respetarte.'),
  (175, 'Cada gota cuenta. Cada día suma. No aflojes.'),
  (176, 'El sacrificio de hoy es la historia que vas a contar.'),
  (177, 'Levantate con hambre de ser mejor que ayer.'),
  (178, 'La disciplina es libertad. La excusa es cárcel.'),
  (179, 'Hoy peleá tu partido. Mañana peleá el siguiente.'),
  (180, 'El que aguanta hasta el día 60 ya ganó, pase lo que pase.'),
  (181, 'No naciste para rendirte fácil. Demostralo.'),
  (182, 'Cada mañana el espejo te pregunta: ¿en serio esta vez?'),
  (183, 'La fuerza mental se entrena igual que el músculo.'),
  (184, 'Hoy movete por el que vas a ser en diciembre.'),
  (185, 'El progreso ama a los que aparecen todos los días.'),
  (186, 'No hay versión mágica de vos. Hay versión trabajada.'),
  (187, 'La comodidad no construyó nada que valga la pena recordar.'),
  (188, 'Cada día que ganás, tu palabra pesa más.'),
  (189, 'Sé constante cuando nadie te ve. Ahí se define todo.'),
  (190, 'El que se mueve gana terreno. El que espera lo pierde.'),
  (191, 'Hoy demostrá con hechos lo que ayer prometiste con palabras.'),
  (192, 'La meta no se alcanza. Se conquista, día por día.'),
  (193, 'Tu excusa tiene fecha de vencimiento. Que sea hoy.'),
  (194, 'El fuerte también tiene días malos. La diferencia es que igual aparece.'),
  (195, 'Cada entrenamiento es un depósito. Cobralo al final.'),
  (196, 'No pares por cansancio. Pará por deber cumplido.'),
  (197, 'La disciplina de hoy es el orgullo de toda la vida.'),
  (198, 'Hoy ganá el partido. Solo eso. Solo hoy.'),
  (199, 'El que llega al día 60 ya no es el mismo que empezó.'),
  (200, 'Vos podés. Siempre pudiste. Hoy demostralo.')
on conflict (id) do update set texto = excluded.texto;
